swagger: '2.0'
info:
  title: Swagger Example
  version: 0.1.0

paths:
  /examples:
     get:
      tags:
       - example
      responses:
        200:
          description: OKAY
          schema:
            $ref: '#/definitions/exampleType'

definitions:
  exampleType:
    properties:
      name:
        type: string
      birthday:
        type: notAType
        format: int32
  
